name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.4'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
    - name: Upload APK
      uses: actions/upload-artifact@v2.2.2
      with:
        name: app
        path: build/app/outputs/flutter-apk/app-release.apk
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.GMAIL_ID}}
        password: ${{secrets.GMAIL_PASSWORD}}
        subject: Github Actions job result
        # Literal body:
        body: Build job of ${{github.repository}} completed successfully!
        to: ${{secrets.GMAIL_ID}}
        from: ${{secrets.GMAIL_ID}}
        # Optional attachments:
        attachments: build/app/outputs/flutter-apk/app-release.apk
